import { ChapterQuest, ImprovedScholar, QuizQuestion, Scholar, StageType } from '../types';

export const SEED_QUESTIONS: QuizQuestion[] = [
  // MATHEMATICS CHAPTER 1: Number Fortress
  {
    id: 'q_m_nf1',
    code: 'PUP-2023-NUM-01',
    subject: 'Mathematics',
    topic: 'Math • Place Value & Face Value',
    grade: 'Class 5',
    difficulty: 'Easy',
    chapterId: 'math_ch1',
    stageType: 'scout',
    question: 'In the number 8,74,923, what is the difference between the place value and face value of the digit 7?',
    hint: 'Place value of 7 is in the ten-thousands place (70,000). Face value is simply 7.',
    options: [
      { key: 'A', text: '69,993' },
      { key: 'B', text: '70,000' },
      { key: 'C', text: '69,930' },
      { key: 'D', text: '7,000' },
    ],
    correctAnswer: 'A',
    explanation: 'Place value of 7 = 70,000. Face value of 7 = 7. Difference = 70,000 - 7 = 69,993.',
  },
  {
    id: 'q_m_nf2',
    code: 'PUP-2022-NUM-02',
    subject: 'Mathematics',
    topic: 'Math • Roman Numerals',
    grade: 'Class 5',
    difficulty: 'Easy',
    chapterId: 'math_ch1',
    stageType: 'scout',
    question: 'Which of the following represents the number 78 in Roman numerals?',
    hint: '50 is L, 20 is XX, 8 is VIII. Combine them.',
    options: [
      { key: 'A', text: 'LXXVIII' },
      { key: 'B', text: 'LXXXVIII' },
      { key: 'C', text: 'LXVIII' },
      { key: 'D', text: 'XXCVIII' },
    ],
    correctAnswer: 'A',
    explanation: '78 = 50 + 20 + 8 = L + XX + VIII = LXXVIII.',
  },
  {
    id: 'q_m_nf3',
    code: 'PUP-2023-NUM-03',
    subject: 'Mathematics',
    topic: 'Math • International & Devanagari Numbers',
    grade: 'Class 5',
    difficulty: 'Medium',
    chapterId: 'math_ch1',
    stageType: 'warrior',
    question: 'What is the sum of the greatest 5-digit number and the smallest 6-digit number formed using digits 0, 3, 5, 7, 9 without repetition?',
    hint: 'Greatest 5-digit: 97,530. Smallest 6-digit cannot start with 0; start with 3: 305,79_ ... wait, only 5 digits given. Smallest 5-digit is 30,579.',
    options: [
      { key: 'A', text: '1,28,109' },
      { key: 'B', text: '1,27,809' },
      { key: 'C', text: '1,28,009' },
      { key: 'D', text: '1,30,000' },
    ],
    correctAnswer: 'A',
    explanation: 'Greatest 5-digit: 97,530. Smallest 5-digit: 30,579. Sum = 97,530 + 30,579 = 1,28,109.',
  },
  {
    id: 'q_m_nf4',
    code: 'PUP-2021-NUM-04',
    subject: 'Mathematics',
    topic: 'Math • Number Operations',
    grade: 'Class 5',
    difficulty: 'Medium',
    chapterId: 'math_ch1',
    stageType: 'warrior',
    question: 'How many thousands make a million?',
    hint: '1 Million = 10,00,000. 1 Thousand = 1,000. Divide.',
    options: [
      { key: 'A', text: '10' },
      { key: 'B', text: '100' },
      { key: 'C', text: '1,000' },
      { key: 'D', text: '10,000' },
    ],
    correctAnswer: 'C',
    explanation: '1,000,000 / 1,000 = 1,000. Exactly one thousand thousands make one million.',
  },
  {
    id: 'q_m_nf_boss',
    code: 'PUP-2023-NUM-BOSS',
    subject: 'Mathematics',
    topic: 'Math • Number Fortress Boss',
    grade: 'Class 5',
    difficulty: 'Hard - Exam PYQ',
    chapterId: 'math_ch1',
    stageType: 'boss',
    question: 'In a 6-digit number, the digit at thousands place is 3 times the digit at units place. If the number ends in 3 and all other digits are 9, what is the number?',
    hint: 'Units place = 3. Thousands place = 3 × 3 = 9. All other digits = 9. So thousands is also 9!',
    options: [
      { key: 'A', text: '999,993' },
      { key: 'B', text: '996,993' },
      { key: 'C', text: '993,993' },
      { key: 'D', text: '989,993' },
    ],
    correctAnswer: 'A',
    explanation: 'Units = 3. Thousands = 3 × 3 = 9. Lakhs = 9, Ten-thousands = 9, Hundreds = 9, Tens = 9. Number = 999,993.',
  },

  // MATHEMATICS CHAPTER 2: Fraction Realm
  {
    id: 'q_m1',
    code: 'PUP-2023-FRC-01',
    subject: 'Mathematics',
    topic: 'Math • Fractions',
    grade: 'Class 5',
    difficulty: 'Easy',
    chapterId: 'math_ch2',
    stageType: 'scout',
    question: 'Which of the following fractions is equivalent to 3/4?',
    hint: 'Multiply numerator and denominator by 3: (3×3)/(4×3) = 9/12.',
    options: [
      { key: 'A', text: '6/10' },
      { key: 'B', text: '9/12' },
      { key: 'C', text: '12/15' },
      { key: 'D', text: '5/8' },
    ],
    correctAnswer: 'B',
    explanation: '3/4 multiplied by 3/3 = 9/12.',
  },
  {
    id: 'q_m2',
    code: 'PUP-2023-FRC-02',
    subject: 'Mathematics',
    topic: 'Math • Fractions',
    grade: 'Class 5',
    difficulty: 'Medium',
    chapterId: 'math_ch2',
    stageType: 'warrior',
    question: 'Solve: 5/8 + 1/4 = ?',
    hint: 'Convert 1/4 into eighths first: 1/4 = 2/8. Then 5/8 + 2/8 = 7/8.',
    options: [
      { key: 'A', text: '6/12' },
      { key: 'B', text: '7/8' },
      { key: 'C', text: '6/8' },
      { key: 'D', text: '5/32' },
    ],
    correctAnswer: 'B',
    explanation: '5/8 + 2/8 = 7/8.',
  },
  {
    id: 'q_m8',
    code: 'PUP-2022-FRC-08',
    subject: 'Mathematics',
    topic: 'Math • Fractions',
    grade: 'Class 5',
    difficulty: 'Medium',
    chapterId: 'math_ch2',
    stageType: 'warrior',
    question: 'If 3/5 of a water tank is 60 liters, what is the total capacity of the tank?',
    hint: '3 parts = 60 liters, so 1 part = 20 liters. 5 parts = 100 liters.',
    options: [
      { key: 'A', text: '80 L' },
      { key: 'B', text: '90 L' },
      { key: 'C', text: '100 L' },
      { key: 'D', text: '120 L' },
    ],
    correctAnswer: 'C',
    explanation: '3/5 = 60 L → 1/5 = 20 L → 5/5 = 100 L.',
  },
  {
    id: 'q_m_frc_boss1',
    code: 'PUP-2023-FRC-BOSS-1',
    subject: 'Mathematics',
    topic: 'Math • Fractions Boss',
    grade: 'Class 5',
    difficulty: 'Hard - Exam PYQ',
    chapterId: 'math_ch2',
    stageType: 'boss',
    question: 'A student spent 2/7 of pocket money on books and 1/3 of the remainder on stationary. If ₹400 is left, find the initial pocket money.',
    hint: 'After books, remainder is 5/7. Spent 1/3 of 5/7, so left with 2/3 of 5/7 = 10/21. 10/21 of total = 400.',
    options: [
      { key: 'A', text: '₹840' },
      { key: 'B', text: '₹750' },
      { key: 'C', text: '₹900' },
      { key: 'D', text: '₹800' },
    ],
    correctAnswer: 'A',
    explanation: 'Remainder after books = 1 - 2/7 = 5/7. Left after stationary = (2/3) × (5/7) = 10/21. (10/21)X = 400 → X = 400 × 21 / 10 = ₹840.',
  },
  {
    id: 'q_m_frc_boss2',
    code: 'PUP-2022-FRC-BOSS-2',
    subject: 'Mathematics',
    topic: 'Math • Decimals Boss',
    grade: 'Class 5',
    difficulty: 'Hard - Exam PYQ',
    chapterId: 'math_ch2',
    stageType: 'boss',
    question: 'Evaluate: (0.35 × 0.35 - 0.15 × 0.15) / 0.20 = ?',
    hint: 'Use the identity a² - b² = (a - b)(a + b). Here a - b = 0.35 - 0.15 = 0.20.',
    options: [
      { key: 'A', text: '0.50' },
      { key: 'B', text: '0.20' },
      { key: 'C', text: '0.70' },
      { key: 'D', text: '0.40' },
    ],
    correctAnswer: 'A',
    explanation: '(a² - b²)/(a - b) = a + b = 0.35 + 0.15 = 0.50.',
  },

  // MATHEMATICS CHAPTER 3: Geometry Labyrinth
  {
    id: 'q_m_geo1',
    code: 'PUP-2023-GEO-01',
    subject: 'Mathematics',
    topic: 'Math • Angles & Triangles',
    grade: 'Class 5',
    difficulty: 'Easy',
    chapterId: 'math_ch3',
    stageType: 'scout',
    question: 'The angles of a triangle are in the ratio 2 : 3 : 4. Find the measure of the smallest angle.',
    hint: 'Sum of angles in a triangle is 180°. Total parts = 2 + 3 + 4 = 9 parts. Smallest = (2/9) × 180°.',
    options: [
      { key: 'A', text: '40°' },
      { key: 'B', text: '30°' },
      { key: 'C', text: '50°' },
      { key: 'D', text: '20°' },
    ],
    correctAnswer: 'A',
    explanation: 'Total ratio parts = 9. 180° / 9 = 20° per part. Smallest angle = 2 × 20° = 40°.',
  },
  {
    id: 'q_m_geo2',
    code: 'PUP-2023-GEO-02',
    subject: 'Mathematics',
    topic: 'Math • Perimeter & Area',
    grade: 'Class 5',
    difficulty: 'Medium',
    chapterId: 'math_ch3',
    stageType: 'warrior',
    question: 'A wire in the shape of a square of side 11 cm is bent into a circle. Find the diameter of the circle.',
    hint: 'Perimeter of square = 4 × 11 = 44 cm. Circumference of circle = πd = (22/7) × d = 44 cm.',
    options: [
      { key: 'A', text: '7 cm' },
      { key: 'B', text: '14 cm' },
      { key: 'C', text: '21 cm' },
      { key: 'D', text: '28 cm' },
    ],
    correctAnswer: 'B',
    explanation: 'Perimeter = 44 cm. Circumference = πd = 44 → (22/7) × d = 44 → d = 14 cm.',
  },
  {
    id: 'q_m_geo_boss',
    code: 'PUP-2022-GEO-BOSS',
    subject: 'Mathematics',
    topic: 'Math • Geometry Boss',
    grade: 'Class 5',
    difficulty: 'Hard - Exam PYQ',
    chapterId: 'math_ch3',
    stageType: 'boss',
    question: 'A rectangular garden of length 25 m and width 15 m has a 2 m wide walking path along its outer boundary. Find the area of the path.',
    hint: 'Outer dimensions: Length = 25 + 4 = 29 m, Width = 15 + 4 = 19 m. Outer Area - Inner Area = Path Area.',
    options: [
      { key: 'A', text: '176 sq. m' },
      { key: 'B', text: '160 sq. m' },
      { key: 'C', text: '184 sq. m' },
      { key: 'D', text: '192 sq. m' },
    ],
    correctAnswer: 'A',
    explanation: 'Outer area = 29 × 19 = 551 sq. m. Inner area = 25 × 15 = 375 sq. m. Path area = 551 - 375 = 176 sq. m.',
  },

  // REASONING & INTELLIGENCE CHAPTER 1: Pattern Sanctuary
  {
    id: 'q_log1',
    code: 'PUP-2023-LOG-01',
    subject: 'Reasoning & Intelligence',
    topic: 'Reasoning • Classification',
    grade: 'Class 5',
    difficulty: 'Easy',
    chapterId: 'logic_ch1',
    stageType: 'scout',
    question: 'Find the odd one out among the following numbers: 27, 64, 125, 144',
    hint: 'Look at cubes vs squares: 3³=27, 4³=64, 5³=125, but 144 is 12².',
    options: [
      { key: 'A', text: '27' },
      { key: 'B', text: '64' },
      { key: 'C', text: '125' },
      { key: 'D', text: '144' },
    ],
    correctAnswer: 'D',
    explanation: '27 (3³), 64 (4³), and 125 (5³) are perfect cubes. 144 is a square (12²).',
  },
  {
    id: 'q_log2',
    code: 'PUP-2023-LOG-02',
    subject: 'Reasoning & Intelligence',
    topic: 'Reasoning • Series',
    grade: 'Class 5',
    difficulty: 'Medium',
    chapterId: 'logic_ch1',
    stageType: 'warrior',
    question: 'Find the next term in the series: 3, 7, 15, 31, 63, ?',
    hint: 'Each term is (previous × 2) + 1. 3×2+1=7, 7×2+1=15...',
    options: [
      { key: 'A', text: '125' },
      { key: 'B', text: '127' },
      { key: 'C', text: '129' },
      { key: 'D', text: '131' },
    ],
    correctAnswer: 'B',
    explanation: '63 × 2 + 1 = 127.',
  },
  {
    id: 'q_l4',
    code: 'PUP-2021-LOG-BOSS',
    subject: 'Reasoning & Intelligence',
    topic: 'Reasoning • Classification',
    grade: 'Class 5',
    difficulty: 'Hard - Exam PYQ',
    chapterId: 'logic_ch1',
    stageType: 'boss',
    question: 'At 3:15, what is the angle between the hour hand and minute hand of a clock?',
    hint: 'The hour hand does not stay frozen at 3; it moves 0.5° every minute!',
    options: [
      { key: 'A', text: '0°' },
      { key: 'B', text: '7.5°' },
      { key: 'C', text: '15°' },
      { key: 'D', text: '30°' },
    ],
    correctAnswer: 'B',
    explanation: 'In 15 minutes, the hour hand moves: 15 × 0.5° = 7.5° past 3. Minute hand is exactly at 3 (90°). Angle = 7.5°.',
  },

  // LANGUAGE CHAPTER 1: Vocabulary Citadel
  {
    id: 'q_lan1',
    code: 'PUP-2023-LAN-01',
    subject: 'Language',
    topic: 'Language • Antonyms',
    grade: 'Class 5',
    difficulty: 'Easy',
    chapterId: 'lang_ch1',
    stageType: 'scout',
    question: 'Choose the exact antonym for the underlined word: "The king showed immense clemency to the travelers."',
    hint: 'Clemency = Mercy / Leniency. Antonym = Harshness / Cruelty.',
    options: [
      { key: 'A', text: 'Kindness' },
      { key: 'B', text: 'Generosity' },
      { key: 'C', text: 'Harshness' },
      { key: 'D', text: 'Bravery' },
    ],
    correctAnswer: 'C',
    explanation: 'Harshness is the true antonym of clemency.',
  },
  {
    id: 'q_lan2',
    code: 'PUP-2023-LAN-02',
    subject: 'Language',
    topic: 'Language • Synonyms',
    grade: 'Class 5',
    difficulty: 'Medium',
    chapterId: 'lang_ch1',
    stageType: 'warrior',
    question: 'Select the word that is most nearly identical in meaning to "CANDID":',
    hint: 'A candid photo is natural and frank. Candid means outspoken and honest.',
    options: [
      { key: 'A', text: 'Deceitful' },
      { key: 'B', text: 'Frank' },
      { key: 'C', text: 'Reserved' },
      { key: 'D', text: 'Polite' },
    ],
    correctAnswer: 'B',
    explanation: 'Candid means honest, straightforward, and frank.',
  },

  // SCIENCE CHAPTER 1: Living Organisms & Nutrition
  {
    id: 'q_sci1',
    code: 'SCI-2023-CH1-01',
    subject: 'Science',
    topic: 'Science • Living Organisms',
    grade: 'Class 5',
    difficulty: 'Easy',
    chapterId: 'science_living_organisms',
    stageType: 'scout',
    question: 'Which of the following organisms shows autotrophic nutrition?',
    hint: 'Autotrophs produce their own food through photosynthesis using sunlight.',
    options: [
      { key: 'A', text: 'Green Plants' },
      { key: 'B', text: 'Fungi' },
      { key: 'C', text: 'Amoeba' },
      { key: 'D', text: 'Human' },
    ],
    correctAnswer: 'A',
    explanation: 'Green plants contain chlorophyll and produce their own food via photosynthesis.',
  },
];

export const DEFAULT_CHAPTER_QUESTS: ChapterQuest[] = [
  // MATHEMATICS REALM
  {
    id: 'math_ch1',
    subject: 'Mathematics',
    chapterNumber: 1,
    title: 'Number Fortress',
    topics: 'Place Value, Roman Numerals & Devanagari',
    icon: '🏰',
    marksWeightage: '12 Marks (Paper 1)',
    stars: 3,
    totalStages: 3,
    currentStage: 3,
    progressPercent: 100,
    isLocked: false,
    requiredLevel: 1,
    stages: [
      { stageNumber: 1, name: 'Stage 1: Scout', type: 'SCOUT', difficulty: 'Easy', questionCount: 2, xpReward: 40, isCompleted: true, isCurrent: false },
      { stageNumber: 2, name: 'Stage 2: Warrior', type: 'WARRIOR', difficulty: 'Medium', questionCount: 2, xpReward: 80, isCompleted: true, isCurrent: false },
      { stageNumber: 3, name: 'Stage 3: BOSS BATTLE 👹', type: 'BOSS', difficulty: 'Hard - Exam PYQ', questionCount: 1, xpReward: 150, isCompleted: true, isCurrent: false },
    ],
    track: 'school',
  },
  {
    id: 'math_ch2',
    subject: 'Mathematics',
    chapterNumber: 2,
    title: 'Fraction Realm',
    topics: 'Proper/Improper, Decimals, Capacity & Shares',
    icon: '⚔️',
    marksWeightage: '16 Marks (Paper 1)',
    stars: 2,
    totalStages: 3,
    currentStage: 2,
    progressPercent: 65,
    isLocked: false,
    requiredLevel: 1,
    stages: [
      { stageNumber: 1, name: 'Stage 1: Scout', type: 'SCOUT', difficulty: 'Easy', questionCount: 2, xpReward: 40, isCompleted: true, isCurrent: false },
      { stageNumber: 2, name: 'Stage 2: Warrior', type: 'WARRIOR', difficulty: 'Medium', questionCount: 2, xpReward: 80, isCompleted: false, isCurrent: true },
      { stageNumber: 3, name: 'Stage 3: BOSS BATTLE 👹', type: 'BOSS', difficulty: 'Hard - Exam PYQ', questionCount: 2, xpReward: 180, isCompleted: false, isCurrent: false, isLocked: true },
    ],
    track: 'school',
  },
  {
    id: 'math_ch3',
    subject: 'Mathematics',
    chapterNumber: 3,
    title: 'Geometry Labyrinth',
    topics: 'Angles, Triangles, Perimeter & Area Formulas',
    icon: '📐',
    marksWeightage: '14 Marks (Paper 1)',
    stars: 1,
    totalStages: 3,
    currentStage: 1,
    progressPercent: 30,
    isLocked: false,
    requiredLevel: 1,
    stages: [
      { stageNumber: 1, name: 'Stage 1: Scout', type: 'SCOUT', difficulty: 'Easy', questionCount: 1, xpReward: 40, isCompleted: true, isCurrent: false },
      { stageNumber: 2, name: 'Stage 2: Warrior', type: 'WARRIOR', difficulty: 'Medium', questionCount: 2, xpReward: 80, isCompleted: false, isCurrent: true },
      { stageNumber: 3, name: 'Stage 3: BOSS BATTLE 👹', type: 'BOSS', difficulty: 'Hard - Exam PYQ', questionCount: 1, xpReward: 150, isCompleted: false, isCurrent: false, isLocked: true },
    ],
    track: 'school',
  },
  {
    id: 'math_ch4',
    subject: 'Mathematics',
    chapterNumber: 4,
    title: 'Unitary Citadel',
    topics: 'Profit & Loss, Percentages, Simple Interest',
    icon: '💰',
    marksWeightage: '16 Marks (Paper 1)',
    stars: 0,
    totalStages: 3,
    currentStage: 1,
    progressPercent: 0,
    isLocked: true,
    requiredLevel: 15,
    track: 'exam',
    stages: [
      { stageNumber: 1, name: 'Stage 1: Scout', type: 'SCOUT', difficulty: 'Easy', questionCount: 3, xpReward: 50, isLocked: true },
      { stageNumber: 2, name: 'Stage 2: Warrior', type: 'WARRIOR', difficulty: 'Medium', questionCount: 3, xpReward: 100, isLocked: true },
      { stageNumber: 3, name: 'Stage 3: BOSS BATTLE 👹', type: 'BOSS', difficulty: 'Hard - Exam PYQ', questionCount: 2, xpReward: 200, isLocked: true },
    ],
  },

  // REASONING & INTELLIGENCE REALM (Exam Track)
  {
    id: 'logic_ch1',
    subject: 'Reasoning & Intelligence',
    chapterNumber: 1,
    title: 'Pattern Sanctuary',
    topics: 'Odd One Out, 90° Clockwise Rotation, Symmetry',
    icon: '🧠',
    marksWeightage: '16 Marks (Paper 2)',
    stars: 2,
    totalStages: 3,
    currentStage: 2,
    progressPercent: 70,
    isLocked: false,
    requiredLevel: 1,
    track: 'exam',
    stages: [
      { stageNumber: 1, name: 'Stage 1: Scout', type: 'SCOUT', difficulty: 'Easy', questionCount: 1, xpReward: 40, isCompleted: true, isCurrent: false },
      { stageNumber: 2, name: 'Stage 2: Warrior', type: 'WARRIOR', difficulty: 'Medium', questionCount: 2, xpReward: 80, isCompleted: false, isCurrent: true },
      { stageNumber: 3, name: 'Stage 3: BOSS BATTLE 👹', type: 'BOSS', difficulty: 'Hard - Exam PYQ', questionCount: 1, xpReward: 150, isCompleted: false, isCurrent: false, isLocked: true },
    ],
  },
  {
    id: 'logic_ch2',
    subject: 'Reasoning & Intelligence',
    chapterNumber: 2,
    title: 'Code & Series Vault',
    topics: 'Number Patterns, Word Analogies, Letter Coding',
    icon: '⚡',
    marksWeightage: '18 Marks (Paper 2)',
    stars: 1,
    totalStages: 3,
    currentStage: 1,
    progressPercent: 40,
    isLocked: false,
    requiredLevel: 1,
    track: 'exam',
    stages: [
      { stageNumber: 1, name: 'Stage 1: Scout', type: 'SCOUT', difficulty: 'Easy', questionCount: 1, xpReward: 40, isCompleted: true, isCurrent: false },
      { stageNumber: 2, name: 'Stage 2: Warrior', type: 'WARRIOR', difficulty: 'Medium', questionCount: 2, xpReward: 80, isCompleted: false, isCurrent: true },
      { stageNumber: 3, name: 'Stage 3: BOSS BATTLE 👹', type: 'BOSS', difficulty: 'Hard - Exam PYQ', questionCount: 1, xpReward: 160, isCompleted: false, isCurrent: false, isLocked: true },
    ],
  },
  {
    id: 'logic_ch3',
    subject: 'Reasoning & Intelligence',
    chapterNumber: 3,
    title: 'Visual Paradox Matrix',
    topics: 'Mirror Images, Water Reflections, Paper Folding',
    icon: '🔮',
    marksWeightage: '16 Marks (Paper 2)',
    stars: 0,
    totalStages: 3,
    currentStage: 1,
    progressPercent: 0,
    isLocked: true,
    requiredLevel: 16,
    track: 'exam',
    stages: [
      { stageNumber: 1, name: 'Stage 1: Scout', type: 'SCOUT', difficulty: 'Easy', questionCount: 2, xpReward: 50, isLocked: true },
      { stageNumber: 2, name: 'Stage 2: Warrior', type: 'WARRIOR', difficulty: 'Medium', questionCount: 3, xpReward: 100, isLocked: true },
      { stageNumber: 3, name: 'Stage 3: BOSS BATTLE 👹', type: 'BOSS', difficulty: 'Hard - Exam PYQ', questionCount: 2, xpReward: 200, isLocked: true },
    ],
  },

  // LANGUAGE REALM
  {
    id: 'lang_ch1',
    subject: 'Language',
    chapterNumber: 1,
    title: 'Vocabulary Citadel',
    topics: 'Antonyms, Synonyms, Proverbs & Spellings',
    icon: '📖',
    marksWeightage: '14 Marks (Paper 1/2)',
    stars: 2,
    totalStages: 3,
    currentStage: 2,
    progressPercent: 80,
    isLocked: false,
    requiredLevel: 1,
    track: 'school',
    stages: [
      { stageNumber: 1, name: 'Stage 1: Scout', type: 'SCOUT', difficulty: 'Easy', questionCount: 1, xpReward: 40, isCompleted: true, isCurrent: false },
      { stageNumber: 2, name: 'Stage 2: Warrior', type: 'WARRIOR', difficulty: 'Medium', questionCount: 1, xpReward: 70, isCompleted: true, isCurrent: false },
      { stageNumber: 3, name: 'Stage 3: BOSS BATTLE 👹', type: 'BOSS', difficulty: 'Hard - Exam PYQ', questionCount: 2, xpReward: 160, isCompleted: false, isCurrent: true },
    ],
  },
  {
    id: 'lang_ch2',
    subject: 'Language',
    chapterNumber: 2,
    title: 'Comprehension Bastion',
    topics: 'Reading Passages, True/False, Inference Riddles',
    icon: '📜',
    marksWeightage: '16 Marks (Paper 1/2)',
    stars: 1,
    totalStages: 3,
    currentStage: 1,
    progressPercent: 25,
    isLocked: false,
    requiredLevel: 1,
    track: 'exam',
    stages: [
      { stageNumber: 1, name: 'Stage 1: Scout', type: 'SCOUT', difficulty: 'Easy', questionCount: 1, xpReward: 40, isCompleted: true, isCurrent: false },
      { stageNumber: 2, name: 'Stage 2: Warrior', type: 'WARRIOR', difficulty: 'Medium', questionCount: 2, xpReward: 80, isCompleted: false, isCurrent: true },
      { stageNumber: 3, name: 'Stage 3: BOSS BATTLE 👹', type: 'BOSS', difficulty: 'Hard - Exam PYQ', questionCount: 1, xpReward: 150, isCompleted: false, isCurrent: false, isLocked: true },
    ],
  },

  // SCIENCE REALM (Class 4-6 School Science)
  {
    id: 'science_living_organisms',
    subject: 'Science',
    chapterNumber: 1,
    title: 'Living Organisms & Nutrition',
    topics: 'Living organisms, growth, development and nutrition',
    icon: '🔬',
    marksWeightage: '16 Marks (Paper 2)',
    stars: 0,
    totalStages: 3,
    currentStage: 1,
    progressPercent: 0,
    isLocked: false,
    requiredLevel: 1,
    track: 'school',
    stages: [
      { stageNumber: 1, name: 'Stage 1: Scout', type: 'SCOUT', difficulty: 'Easy', questionCount: 5, xpReward: 40, isCompleted: false, isCurrent: true, isLocked: false },
      { stageNumber: 2, name: 'Stage 2: Warrior', type: 'WARRIOR', difficulty: 'Medium', questionCount: 4, xpReward: 80, isCompleted: false, isCurrent: false, isLocked: true },
      { stageNumber: 3, name: 'Stage 3: BOSS BATTLE 👹', type: 'BOSS', difficulty: 'Hard - Exam Special', questionCount: 2, xpReward: 150, isCompleted: false, isCurrent: false, isLocked: true },
    ],
  },
];

export const SIMULATED_PEERS: Scholar[] = [
  { rank: 1, name: 'Rohan M.', city: 'Ambajogai', school: 'Kholeshwar Vidyalaya, Ambajogai', grade: 'Class 5', division: '5-A', points: 1140, accuracy: 96, isUser: false },
  { rank: 2, name: 'Ananya S.', city: 'Ambajogai', school: 'Kholeshwar Vidyalaya, Ambajogai', grade: 'Class 5', division: '5-B', points: 1080, accuracy: 94, isUser: false },
  { rank: 3, name: 'Omkar K.', city: 'Ambajogai', school: 'Kholeshwar Vidyalaya, Ambajogai', grade: 'Class 5', division: '5-A', points: 1020, accuracy: 91, isUser: false },
  { rank: 4, name: 'Tanvi D.', city: 'Ambajogai', school: 'Kholeshwar Vidyalaya, Ambajogai', grade: 'Class 5', division: '5-B', points: 960, accuracy: 89, isUser: false },
  { rank: 5, name: 'Pranav K.', city: 'Ambajogai', school: 'Kholeshwar Vidyalaya, Ambajogai', grade: 'Class 5', division: '5-A', points: 910, accuracy: 88, isUser: false },
  { rank: 6, name: 'Siddhesh P.', city: 'Ambajogai', school: 'Kholeshwar Vidyalaya, Ambajogai', grade: 'Class 5', division: '5-B', points: 860, accuracy: 85, isUser: false },
  { rank: 8, name: 'Meera J.', city: 'Ambajogai', school: 'Kholeshwar Vidyalaya, Ambajogai', grade: 'Class 5', division: '5-A', points: 790, accuracy: 82, isUser: false },
];

export const SIMULATED_SCHOOL_PEERS: Scholar[] = [
  { rank: 1, name: 'Rohan M.', city: 'Ambajogai', school: 'Kholeshwar Vidyalaya, Ambajogai', grade: 'Class 5', division: '5-A', points: 580, accuracy: 95, isUser: false },
  { rank: 2, name: 'Ananya S.', city: 'Ambajogai', school: 'Kholeshwar Vidyalaya, Ambajogai', grade: 'Class 5', division: '5-B', points: 510, accuracy: 92, isUser: false },
  { rank: 3, name: 'Omkar K.', city: 'Ambajogai', school: 'Kholeshwar Vidyalaya, Ambajogai', grade: 'Class 5', division: '5-A', points: 480, accuracy: 90, isUser: false },
  { rank: 4, name: 'Tanvi D.', city: 'Ambajogai', school: 'Kholeshwar Vidyalaya, Ambajogai', grade: 'Class 5', division: '5-B', points: 420, accuracy: 88, isUser: false },
  { rank: 5, name: 'Pranav K.', city: 'Ambajogai', school: 'Kholeshwar Vidyalaya, Ambajogai', grade: 'Class 5', division: '5-A', points: 390, accuracy: 86, isUser: false },
  { rank: 6, name: 'Siddhesh P.', city: 'Ambajogai', school: 'Kholeshwar Vidyalaya, Ambajogai', grade: 'Class 5', division: '5-B', points: 350, accuracy: 84, isUser: false },
];

export const MOST_IMPROVED_SCHOLARS: ImprovedScholar[] = [
  { name: 'Shaurya M.', city: 'Ambajogai', prevAcc: 55, currAcc: 74, growth: 19, icon: '🔥', color: 'secondary' },
  { name: 'Anaya D.', city: 'Ambajogai', prevAcc: 48, currAcc: 72, growth: 24, icon: '🌟', color: 'tertiary' },
];
